// Generated by CoffeeScript 1.4.0

/*
Pubber is a library aimed to make it easier to organize subscriptions, unsubscriptions, and publishes
*/


(function() {
  var logger, pb;

  console.log('pubber init');

  window.app = [];

  pb = pubsub;

  logger = function(topics, data) {
    console.log('now subscribed to: ' + topics);
    return console.log(data);
  };

  app.create = function(event) {
    if (!app.subscribed) {
      return app.total = pb.subscribe(event, logger);
    }
  };

  app.read = function(event, obj) {
    return pb.publish(event, obj);
  };

  app.update = function(event, pubval) {
    return pb.publish(event, pubval);
  };

  app.del = function(event) {
    return pb.unsubscribe(event);
  };

  app.pubber = function(event, arg) {
    app.create(event);
    return app.read(event, arg);
  };

  app.pubber.revoke = function(event) {
    return app.del(event);
  };

}).call(this);
