// Generated by CoffeeScript 1.4.0
(function() {
  var createElem, publishEvent, showLog, subscribeEvent, unsubscribeExample;

  createElem = function(wrapElem, tag, txt) {
    var domTag, textNode, wrapper;
    domTag = document.createElement(tag);
    textNode = document.createTextNode(txt);
    domTag.appendChild(textNode);
    wrapper = document.getElementById(wrapElem);
    return wrapper.appendChild(domTag);
  };

  showLog = function(topics, data) {
    console.log('from subscribed');
    return console.log(topics + ': ' + data);
  };

  window.pubber = window.pubber || [];

  window.pubber.logging = {
    holders: {
      log: document.getElementById('log'),
      subscriptions: 'subscriptions',
      published: document.getElementById('published'),
      unsubscribed: document.getElementById('unsubscribed')
    },
    messages: {
      warn: 'warning',
      notify: 'notify',
      alerter: 'alerter'
    }
  };

  subscribeEvent = function(eventName, method) {
    console.log('expect event named: ' + eventName);
    pubsub.subscribe(eventName, method);
    return createElem(pubber.logging.holders.subscriptions, 'li', method);
  };

  subscribeEvent('custom', showLog());

  publishEvent = function(eventName, method) {
    console.log('expect publishEvent');
    pubsub.publish(eventName, method);
    return createElem('body-tag', 'div', 'bar');
  };

  publishEvent();

  unsubscribeExample = function() {
    return setTimeout(function() {
      pubsub.unsubscribe('user');
      return console.log('user unsubscribed', 0);
    });
  };

}).call(this);
